# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('name',), 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
    ]
