# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160409_1927'),
        ('chat', '0002_auto_20160602_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='mensagem')),
                ('pub_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='core.Profile')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.RemoveField(
            model_name='chat',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='to_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='chat.Chat'),
        ),
    ]
