from django.conf.urls import url

from core import views

urlpatterns = [
    url(regex=r'^$',
        view=views.IndexView.as_view(),
        name='index'),
    url(regex=r'^confirmation/email/(?P<email_code>[\w-]+)/$',
        view=views.ConfirmationEmail.as_view(),
        name='confirmation_email'),
    url(regex=r'^api/confirmation/phone/(?P<phone_code>[\w-]+)/$',
        view=views.ConfirmationPhone.as_view(),
        name='confirmation_phone'),

    # User API
    url(regex=r'^api/users/feed/$',
        view=views.UserFeedList.as_view(),
        name='user_feed_list'),
    url(regex=r'^api/users/$',
        view=views.UserList.as_view(),
        name='user_list'),
    url(regex=r'^api/users/(?P<pk>[0-9]+)/$',
        view=views.UserRetrieve.as_view(),
        name='user_retrieve'),
    url(regex=r'^api/users/logged_user/$',
        view=views.LoggedUserRetrieve.as_view(),
        name='logged_user_retrieve'),

    # Profile API
    url(regex=r'^api/profiles/$',
        view=views.ProfileListView.as_view(),
        name='profile_list'),
    url(regex=r'^api/profiles/logout/$',
        view=views.ProfileLogoutView.as_view(),
        name='profile_logout'),
    url(regex=r'^api/profiles/(?P<pk>[0-9]+)/$',
        view=views.ProfileUpdateView.as_view(),
        name='profile_detail'),
    url(regex=r'^api/profiles/(?P<pk>[0-9]+)/add_mate/$',
        view=views.ProfileAddMateView.as_view(),
        name='profile_add_mate'),
    url(regex=r'^api/profiles/pending_mates/$',
        view=views.ProfilePendingMatesView.as_view(),
        name='profile_pending_mates'),
    url(regex=r'^api/profiles/(?P<pk>[0-9]+)/accept_mate/$',
        view=views.ProfileAcceptMateView.as_view(),
        name='profile_accept_mate'),
    url(regex=r'^api/profiles/(?P<pk>[0-9]+)/reject_mate/$',
        view=views.ProfileRejectMateView.as_view(),
        name='profile_reject_mate'),
    url(regex=r'^api/profiles/(?P<pk>[0-9]+)/delete_mate/$',
        view=views.ProfileDeleteMateView.as_view(),
        name='profile_delete_mate'),
    url(regex=r'^api/profiles/(?P<pk>[0-9]+)/cancel_mate/$',
        view=views.ProfileCancelMateView.as_view(),
        name='profile_cancel_mate'),
    url(regex=r'^api/profiles/mates/$',
        view=views.ProfileMatesView.as_view(),
        name='profile_mates'),
    url(regex=r'^api/profiles/reset_email_code/$',
        view=views.ProfileResetEmailCodeView.as_view(),
        name='profile_reset_email_code'),
    url(regex=r'^api/profiles/reset_phone_code/$',
        view=views.ProfileResetPhoneCodeView.as_view(),
        name='profile_reset_phone_code'),
    url(regex=r'^api/profiles/confirm_phone_code/$',
        view=views.ProfileConfirmPhoneCodeView.as_view(),
        name='profile_confirm_phone_code'),
    url(regex=r'^api/profiles/polls/$',
        view=views.ProfilePollsView.as_view(),
        name='profile_polls'),
]
