# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20160406_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='deslikes',
            field=models.IntegerField(default=0, verbose_name='Deslikes'),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
