# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20160409_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['created_at'], 'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AddField(
            model_name='poll',
            name='created_at',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 19, 24, 57, 224438, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerrate',
            name='rate',
            field=models.CharField(choices=[(b'L', 'Like')], default=b'L', max_length=2, verbose_name='Rate'),
        ),
    ]
